//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.atgardner.OMFG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.atgardner.OMFG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Noam &quot;Amtrak&quot; Gal (http://pct14.blogspot.com/p/offline-maps.html) using OMFG (atgardner.github.com/OfflineMapFileGenerator)
        ///Source: {0}.
        /// </summary>
        internal static string CopyrightTemplate {
            get {
                return ResourceManager.GetString("CopyrightTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear-map
        /////set-geo-bounds -118.4765625, 36.5978891330702, -118.125, 36.8796206050268
        ///set-geo-bounds {0}, {1}, {2}, {3}
        ///move-pos x={0} y={1} zoom=10
        ///set-setting name=map.coastline.mode value=loose
        ///download-osm-overpass query=&quot;(node($b$);rel(bn)-&gt;.x;way($b$);node(w)-&gt;.x;rel(bw););out;&quot;
        /////set-source index=1 visible=false
        ///run-python file=&quot;Python\AddWayLengthTags.py&quot;
        ///load-source Cache\Forests.osm
        ///// SRTM3/SRTM1/SRTMV3R3/SRTMV3R1/VF.Alps
        ///set-dem-source name=SRTM1
        ///generate-relief-igor intensity=6 color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaperitiveScriptTemplate {
            get {
                return ResourceManager.GetString("MaperitiveScriptTemplate", resourceCulture);
            }
        }
    }
}
